version: '3.7'

services:
  app:
    container_name: streamlit-app
    image: siarheisvila/sbc-processor:1.0
    pull_policy: always
    ports:
      - '80:8501'
    env_file:
      - ./.env
    volumes:
      - /app/logs:/app/logs