version: '3.7'

services:
  app:
    container_name: streamlit-app
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '80:8501'
    env_file:
      - ./.env
    volumes:
      - /app/logs:/app/logs